version: '3.4'

networks:
  dev_network:
    driver: bridge
    external: true

volumes:
  shared: {}

services:
  monitoring:
    image: "prom/prometheus:v2.32.1"
    container_name: "prometheus_monitoring"
    ports:
      - 9090:9090  
    volumes:
      - ./shared/prometheus:/etc/prometheus/
      - ./shared/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/config/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - dev_network
