version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
       - "${SHARED}/data/postgres-data:/data/postgres"
       - "${SHARED}/data/postgres:/var/lib/postgresql/data"
       - "${SHARED}/data/pgdata:/var/lib/postgresql/data/pgdata"
       - "./scripts:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge   

volumes:
  shared: 
    driver: local