version: "3"
services:
 
  mysql8.0:
    image: mysql
    container_name: ${MYSQL_CONTAINER_NAME_PREFIX}
    ports:
      - 3380:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - ./shared/my.cnf:/root/.my.cnf:ro
      - ./shared/mysql8.0/conf.d:/etc/mysql/conf.d:ro
      - ./shared/mysql8.0/logs:/var/log/mysql:rw
      - ./shared/mysql8.0/initdb.d:/docker-entrypoint-initdb.d:ro
      - ./shared/common:${MOUNTED_SHARED_DIRECTORY}:ro
      - ./shared/auto-generate:/auto-generate:rw
    networks:
      - dev_network

  adminer:
    image: adminer
    ports:
      - 8089:8080
    networks:
      - dev_network
    restart: always
    depends_on: 
      - mysqldb

networks:
  dev_network:
    driver: bridge
    external: true
  