version: "3"
services:
  mysql5.5:
    image: mysql:5.5
    container_name: ${MYSQL_CONTAINER_NAME_PREFIX}5.5
    ports:
      - 3355:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - ./my.cnf:/root/.my.cnf:ro
      - ./mysql5.5/conf.d:/etc/mysql/conf.d:ro
      - ./mysql5.5/logs:/var/log/mysql:rw
      - ./mysql5.5/initdb.d:/docker-entrypoint-initdb.d:ro
      - ./common:${MOUNTED_SHARED_DIRECTORY}:ro
      - ./auto-generate:/auto-generate:rw
  mysql5.6:
    image: mysql:5.6
    container_name: ${MYSQL_CONTAINER_NAME_PREFIX}5.6
    ports:
      - 3356:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - ./my.cnf:/root/.my.cnf:ro
      - ./mysql5.6/conf.d:/etc/mysql/conf.d:ro
      - ./mysql5.6/logs:/var/log/mysql:rw
      - ./mysql5.6/initdb.d:/docker-entrypoint-initdb.d:ro
      - ./common:${MOUNTED_SHARED_DIRECTORY}:ro
      - ./auto-generate:/auto-generate:rw
  mysql5.7:
    image: mysql:5.7
    container_name: ${MYSQL_CONTAINER_NAME_PREFIX}5.7
    ports:
      - 3357:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - ./my.cnf:/root/.my.cnf:ro
      - ./mysql5.7/conf.d:/etc/mysql/conf.d:ro
      - ./mysql5.7/logs:/var/log/mysql:rw
      - ./mysql5.7/initdb.d:/docker-entrypoint-initdb.d:ro
      - ./common:${MOUNTED_SHARED_DIRECTORY}:ro
      - ./auto-generate:/auto-generate:rw
  mysql8.0:
    image: mysql:8.0
    container_name: ${MYSQL_CONTAINER_NAME_PREFIX}8.0
    ports:
      - 3380:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - ./my.cnf:/root/.my.cnf:ro
      - ./mysql8.0/conf.d:/etc/mysql/conf.d:ro
      - ./mysql8.0/logs:/var/log/mysql:rw
      - ./mysql8.0/initdb.d:/docker-entrypoint-initdb.d:ro
      - ./common:${MOUNTED_SHARED_DIRECTORY}:ro
      - ./auto-generate:/auto-generate:rw

  mariadb10.0:
    image: mariadb:10.0
    container_name: ${MARIADB_CONTAINER_NAME_PREFIX}10.0
    ports:
      - 3310:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - ./my.cnf:/root/.my.cnf:ro
      - ./mariadb10.0/conf.d:/etc/mysql/conf.d:ro
      - ./mariadb10.0/logs:/var/log/mysql:rw
      - ./mariadb10.0/initdb.d:/docker-entrypoint-initdb.d:ro
      - ./common:${MOUNTED_SHARED_DIRECTORY}:ro
      - ./auto-generate:/auto-generate:rw
  mariadb10.1:
    image: mariadb:10.1
    container_name: ${MARIADB_CONTAINER_NAME_PREFIX}10.1
    ports:
      - 3311:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - ./my.cnf:/root/.my.cnf:ro
      - ./mariadb10.1/conf.d:/etc/mysql/conf.d:ro
      - ./mariadb10.1/logs:/var/log/mysql:rw
      - ./mariadb10.1/initdb.d:/docker-entrypoint-initdb.d:ro
      - ./common:${MOUNTED_SHARED_DIRECTORY}:ro
      - ./auto-generate:/auto-generate:rw
  mariadb10.2:
    image: mariadb:10.2
    container_name: ${MARIADB_CONTAINER_NAME_PREFIX}10.2
    ports:
      - 3312:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - ./my.cnf:/root/.my.cnf:ro
      - ./mariadb10.2/conf.d:/etc/mysql/conf.d:ro
      - ./mariadb10.2/logs:/var/log/mysql:rw
      - ./mariadb10.2/initdb.d:/docker-entrypoint-initdb.d:ro
      - ./common:${MOUNTED_SHARED_DIRECTORY}:ro
      - ./auto-generate:/auto-generate:rw
  mariadb10.3:
    image: mariadb:10.3
    container_name: ${MARIADB_CONTAINER_NAME_PREFIX}10.3
    ports:
      - 3313:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - ./my.cnf:/root/.my.cnf:ro
      - ./mariadb10.3/conf.d:/etc/mysql/conf.d:ro
      - ./mariadb10.3/logs:/var/log/mysql:rw
      - ./mariadb10.3/initdb.d:/docker-entrypoint-initdb.d:ro
      - ./common:${MOUNTED_SHARED_DIRECTORY}:ro
      - ./auto-generate:/auto-generate:rw
