apiVersion: v1
kind: Pod
metadata:
  name: sistemas-noticias
  labels:
    app: sistemas-noticias
spec:
  containers:
  - name: sistemas-noticias-container
    image: aluracursos/sistema-noticias:1
    ports:
      - containerPort: 80
    envFrom:
      - configMapRef:
          name: sistema-configmap