version: '2.1'

services:
  activemq_artemis:
    image: activemq_artemis
    build: .
    environment:
      ARTEMIS_USERNAME: admin
      ARTEMIS_PASSWORD: admin
    ports:
      - 61616:61616
      - 8161:8161