# Use root/p102030 as user/password credentials
version: '3.5'


networks:
  dev_network:
    driver: bridge
    external: true

volumes:
  shared: {}
  schemas: {}

services:

  mongo:
    image: mongo    
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: p102030 
    ports:
        - "27017:27017"
    networks:
      - dev_network
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: p102030
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: appuser
      ME_CONFIG_BASICAUTH_PASSWORD: appuser!
    depends_on:
      - mongo 
    links:
      - mongo 
    networks:
      - dev_network