version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:12.6
    environment: 
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-p102030}
      PGDATA: /data/postgres
    volumes:
       - "./data/postgres-data:/data/postgres"
       - "./data/postgres:/var/lib/postgresql/data"
       - "./data/pgdata:/var/lib/postgresql/data/pgdata"
       - "./schemas:/schemas"
    ports:
      - "5432:5432"
    networks:
      - network-postgre
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:5.0
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - network-postgre
    restart: unless-stopped
    depends_on: 
      - postgres

  sonarqube:
    container_name: sonar_community
    image: sonarqube:8.7.1-community
    depends_on:
      - postgres
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9000:9000"
    networks:
      - network-postgre
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      SONAR_JDBC_USERNAME: postgres
      SONAR_JDBC_PASSWORD: p102030
    volumes:
      - ./sonar/sonarqube_data:/opt/sonarqube/data
      - ./sonar/sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonar/sonarqube_logs:/opt/sonarqube/logs
      - ./sonar/sonarqube_temp:/opt/sonarqube/temp
    restart: unless-stopped

networks:
  network-postgre:
    driver: bridge
