version: '3.4'

networks:
  dev_network:
    driver: bridge
    external: true

volumes:
  shared: {}
  schemas: {}

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ./docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - dev_network