version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-p102030}
      PGDATA: /data/postgres
    volumes:
      - "./shared/postgres/data/postgres:/data/postgres"
      - "./shared/postgres/var/lib/postgresql/data:/var/lib/postgresql/data"
      - "./shared/postgres/var/lib/postgresql/data/pgdata:/var/lib/postgresql/data/pgdata"
      - "./schemas:/schemas"
    ports:
      - "5432:5432"
    networks:
      - environment_dev
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - environment_dev
    restart: unless-stopped
    depends_on:
      - postgres


networks:
  environment_dev:
    driver: bridge

volumes:
  shared: {}
  schemas: {}
