version: "3.9"

networks:
  dev_network:
    driver: bridge
    external: true

volumes:
  shared: {}

services:
  sonarqube:
    container_name: sonar_community
    image: sonarqube:8.9.2-community
#    depends_on:
#      - postgres
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9000:9000"
    networks:
      - dev_network
    #    restart: unless-stopped
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://hostdb2:5432/sonar
      SONAR_JDBC_USERNAME: postgres
      SONAR_JDBC_PASSWORD: p102030
    volumes:
      - "./shared/sonarqube/opt/sonarqube/data:/opt/sonarqube/data"
      - "./shared/sonarqube/opt/sonarqube/extensions:/opt/sonarqube/extensions"
      - "./shared/sonarqube/opt/sonarqube/logs:/opt/sonarqube/logs"
      - "./shared/sonarqube/opt/sonarqube/temp:/opt/sonarqube/temp"
