version: "3.9"

networks:
  dev_network:
    driver: bridge
    external: true

volumes:
  shared: {}
  schemas: {}

services:
  postgres:
    container_name: postgres
    image: postgres:14
    hostname: hostdb2
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-p102030}
      PGDATA: /data/postgres
    volumes:
      - "./shared/postgresql/postgresdata/postgres:/data/postgres"
      - "./shared/postgresql/var/lib/postgresql/data:/var/lib/postgresql/data"
      - "./shared/postgresql/var/lib/postgresql/data/pgdata:/var/lib/postgresql/data/pgdata"
      - "./scritps:/docker-entrypoint-initdb.d"
      - "./schemas:/schemas"
    ports:
      - "5432:5432"
    networks:
      - dev_network
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - dev_network
    depends_on:
      - postgres
  sonarqube:
    image: bitnami/sonarqube
    ports:
      - '7981:9000'
    volumes:
      - "./shared/sonarqube/sonarqube_data:/bitnami" 
      - "./shared/sonarqube/logs:/opt/bitnami/sonarqube/logs" 
    depends_on:
      - postgres
    networks:
      - dev_network
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      ALLOW_EMPTY_PASSWORD: yes
      SONARQUBE_DATABASE_HOST: postgres
      SONARQUBE_DATABASE_PORT_NUMBER: 5432      
      SONARQUBE_DATABASE_NAME: sonardb
      SONARQUBE_DATABASE_USER: sonarapp
      SONARQUBE_DATABASE_PASSWORD: sonarapp
  keycloak:
    image: bitnami/keycloak
    environment:
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_MANAGEMENT_PASSWORD: admin
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_NAME: keycloakdb
      KEYCLOAK_DATABASE_USER: keycloakapp
      KEYCLOAK_DATABASE_PASSWORD: keycloakapp
      SONARQUBE_PASSWORD: p102030
    depends_on:
      - postgres 
    networks:
      - dev_network
    ports:
      - "7080:8080"
      - "7443:8443"

