
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # Porta padrão do RabbitMQ
      - "15672:15672"  # Porta da interface de gerenciamento
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    

volumes:
  rabbitmq_data:
    name: rabbitmq_data