apiVersion: v1
kind: Pod
metadata:
  name: db-noticias
  labels:
    app: db-noticias
spec:
  containers:
  - name: db-noticias-containers
    image: aluracursos/mysql-db:1
    ports:
      - containerPort: 3306
    envFrom:
      - configMapRef:
          name: db-configmap
    
  # env:
  #    - name: MYSQL_DATABASE
  #      valueFrom:
  #        configMapKeyRef:
  #          key: MYSQL_DATABASE
  #          name: db-configmap
  #    - name: MYSQL_PASSWORD
  #      valueFrom:
  #        configMapKeyRef:
  #          key: MYSQL_PASSWORD
  #          name: db-configmap
  #    - name: MYSQL_ROOT_PASSWORD
  #      valueFrom:
  #        configMapKeyRef:
  #          key: MYSQL_ROOT_PASSWORD
  #          name: db-configmap
      
